### ISSUE TITLE
cannot pickle lamdba functions

### ISSUE THREAD

**Issue by jkrauska** [cevans87/atools#61]
I think dill resolves this?

**Comment by cevans87** [comment]
> I think dill resolves this?

Looks like it does.

I'm not sure being able to pickle lambda functions is super important for the memoize decorator. I found that my own use-case where I discovered this problem was just a bad idea. If there's a good argument for making it posssible to memoize a lambda function, I'll look closer at adding `dill` as a dependency.

**Comment by cevans87** [comment]
I finally got around to really looking at this and was able to repro with this test.
```python3
def test_unpickleable_return_type_with_db_does_not_raise(db_path: Path) -> None:
    foo_body = MagicMock()
    bar_body = MagicMock()

    @memoize(db_path=db_path)
    def foo() -> Callable[[], None]:
        foo_body()

        return lambda: bar_body()

    foo()()
    foo()()

    assert foo_body.call_count == 1
    assert bar_body.call_count == 2
 ```
 I'd prefer not to add `dill` as a dependency as it won't commonly be needed and it might not cover all similar cases in the future.
 
 However, I can see why we'd want to allow broader pickling behavior than what the default `pickle` provides. I think we could add an optional `pickle` argument to memoize. In my own projects, I'd likely use it to define a custom memoize implementation, if needed.
 ```python3
 # In custom_atools.py
 from atools import memoize
 import dill as _dill
 
 memoize_db = memoize(db_path='~/.memoize`, pickle=_dill)
 
 # In main.py
 from custom_atools import memoize_db
 
 
 @memoize_db
 def foo() -> Callable[[], None]:
    return lambda None
    
    
 if __name__ == '__main__':
   foo()()
```

Sound sane to you?

**Comment by cevans87** [comment]
Release v0.14.0 with these changes.
